apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-vno-setting
spec:
  forms:
    - group: general
      label: 基本设置
      formSchema:
        - $formkit: text
          name: welcome_message
          label: 欢迎信息
        - $formkit: attachment
          name: cover_image
          label: 首页背景图片
        - $formkit: select
          name: cover_color
          label: 首页背景颜色
          value: red
          options:
            - value: blue
              label: blue
            - value: green
              label: green
            - value: purple
              label: purple
            - value: red
              label: red
            - value: orange
              label: orange
            - value: slate
              label: slate
            - value: empty
              label: 空
        - $formkit: text
          name: blog_button_title
          label: 博客按钮名称
          value: Blog
        - $formkit: text
          name: blog_button_description
          label: 博客按钮描述
          value: Visit blog
    - group: sns
      label: 社交资料设置
      formSchema:
        - $formkit: text
          name: weibo
          label: 微博
        - $formkit: text
          name: github
          label: GitHub 链接
        - $formkit: text
          name: google_plus
          label: Google Plus
        - $formkit: text
          name: email
          label: Email
